export const dummy = {
  session: {
    expires_at: 1685051806,
    expires_in: 3166,
    token_type: "bearer",
    access_token:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjg1MDUxODA2LCJzdWIiOiIwNzZhNzVhMy1kOTNhLTRjMmUtOTZlNi0yNmFlNTIxMzk0YTIiLCJlbWFpbCI6IndvbkBzaWduYXR1cmUuc3R1ZGlvIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2ODQ4NTQxNzh9XSwic2Vzc2lvbl9pZCI6ImIwY2M3NzA4LTQ5ODItNDRmYy05MjIzLTIzNmNlOTBjN2FiYiJ9.9owtRQt2j7-VHvEbgku8aSqY7baZsYFqF_OnrwFEkog",
    refresh_token: "EQmy0k964R_g2k96w28-Pw",
    provider_token: null,
    provider_refresh_token: null,
    user: {
      id: "076a75a3-d93a-4c2e-96e6-26ae521394a2",
      aud: "authenticated",
      email: "won@signature.studio",
      phone: "",
      app_metadata: {
        provider: "email",
        providers: ["email"],
      },
      user_metadata: {},
      role: "authenticated",
      aal: "aal1",
      amr: [
        {
          method: "password",
          timestamp: 1684854178,
        },
      ],
      session_id: "b0cc7708-4982-44fc-9223-236ce90c7abb",
    },
  },
  contents: {
    created_at: "2023-05-20T22:54:23.463986+00:00",
    updated_at: "2023-05-23T06:37:00.899615+00:00",
    name: "Quotation",
    content:
      "Payments are to be made (by credit card or Internet transfer) according to the schedule below. Unless advised otherwise, your credit card (supplied to us at the time of booking) will be charged accordingly. Kindly refer to the Payments Summary found on your provisional or e-ticket issued to you for more details.\r\n{payment_schedule}\r\n\r\nImportant: Please read and understand the terms and conditions found in this document and at the following links below.\r\n{agreement_terms}\r\n\r\nAny optional or extra items are to be paid directly to {supplier_name} at the time of pick-up. Please refer to your e-Ticket for more details.\r\nPlease ensure that you have sufficient funds in your credit card to pay the bond. Information on applicable bond charges can be found in this document.\r\nPlease ensure that you pick-up and drop-off your rental vehicle during depot business hours to avoid any inconvenience or extra charges. Depot addresses and booking times can be found in this document.",
    image: null,
    type: "template_quote",
    description:
      "If you have just entered a self quote request, please allow us 24 hours or less to check availability and price. Quotes are valid for 7 days or till Sunday night 6pm.",
    id: "f64c2518-9cf3-4fc7-83b5-d19c712e85af",
    categories: null,
    status: true,
    richtext: [],
    featured: false,
    slug: null,
    rank: null,
    caption:
      "<p>Payments are to be made (by credit card or Internet transfer) according to the schedule below. Unless advised otherwise, your credit card (supplied to us at the time of booking) will be charged accordingly. Kindly refer to the Payments Summary found on your provisional or e-ticket issued to you for more details.</p><p>{payment_schedule}</p><p></p><p>Important: Please read and understand the terms and conditions found in this document and at the following links below.</p><p>{agreement_terms}</p><p></p><p>Any optional or extra items are to be paid directly to {supplier_name} at the time of pick-up. Please refer to your e-Ticket for more details.</p><p>Please ensure that you have sufficient funds in your credit card to pay the bond. Information on applicable bond charges can be found in this document.</p><p>Please ensure that you pick-up and drop-off your rental vehicle during depot business hours to avoid any inconvenience or extra charges. Depot addresses and booking times can be found in this document.</p>",
    images: null,
    attachment: null,
  },
  site: {
    contact: {
      type: "contact",
      name: "Any question's for us",
      subtitle: "Get in touch",
      description:
        "If you need any further info, feel free to get in touch after 10am EST and we will get back to your as soon as possible.\nAustralia 4 Wheel Drive Rentals\nFree Call Within \nAustralia 1800-107371\nInternational Call +61 (0) 8 7999 7511",
    },
    hotline: "Free Call Within Australia 1-800-107371",
    icon: "366d91e1-3e20-473e-a679-96855cb31b04.png",
    title:
      "Australia 4 Wheel Drive Rentals - self drive road trips across Australia the Australian 4wd rental specialists since 2002",
    color: "#1eb314",
    logo: "bd84cb24-4be4-4c79-94cc-ff4fc6fbbd07.png",
    description:
      "Looking for an unforgettable self-drive adventure in Australia? Look no further than Australia 4 Wheel Drive Rentals. Our fleet of rugged 4WD vehicles, equipped with all the necessary safety features and accessories, are perfect for exploring Australia's remote and rugged landscapes. With locations in all major cities, we offer personalized itinerary planning, expert advice, and a range of accessories and equipment to help you make the most of your journey. Book your rental today and get ready to explore the great outdoors of Australia like never before.",
    keywords:
      "Australia 4 Wheel Drive Rentals, 4WD rentals, Australia 4wd rentals, 4X4 hire, Australia, self-drive, off-road driving, camping, rooftop tents, Toyota Land Cruisers, Toyota Prado rentals, Mitsubishi Pajeros, itinerary planning, Australia travel, adventure travel, four wheel drive hire, darwin 4wd's.",
  },
  letterhead: {
    content:
      "Postal Address: GPO Box 3410, Darwin, NT 0801\r\nTel: 1-800-107-371 OR 08-7999-7511  (Australia)\r\nTel: +61 -7999-7511  (International)\r\nEmail: info@australia4wdrentals.com",
    description: "ABN No: 54 561 356 425 ",
    name: "Australia 4 Wheel Drive Rentals",
  },
  quote: {
    id: 38,
    created_at: "2023-05-24T03:32:11.741852+00:00",
    updated_at: "2023-05-24T03:32:11.741852+00:00",
    details: {
      date_issue: "2023-05-24T03:31:42.905Z",
      date_book: "2023-05-24T03:31:42.905Z",
      date_start: "2023-10-31T16:00:00.000Z",
      date_end: "2023-11-09T16:00:00.000Z",
      pax: "2023-05-24T03:31:42.906Z",
      duration: 10,
      min_days: 5,
      rates_type: "flex",
      rates_nett: 1,
      rates_gross: 1.25,
      pickup: {
        id: "1e655c35-e21c-4634-88e3-d5f00901f249",
        name: "Darwin",
      },
      dropoff: {
        id: "1e655c35-e21c-4634-88e3-d5f00901f249",
        name: "Darwin",
      },
      vehicle: {
        id: "dbed6fc4-1901-4871-930c-9fd095ec988a",
        name: "Adventure 4wd Camper",
        image:
          "https://rixauffklvvhkfkwrpme.supabase.co/storage/v1/render/image/public/contents/8deded15-906e-4e3c-b292-9ad7824d7179.gif?width=600&height=600&resize=contain",
        excerpt:
          "The compact Adventure Camper is perfect for those interested in a real outback adventure. Roomier, more fuel capacity and cooking facilities make this 4WD campervan ideal for thrill seeking couples.",
        slug: "adventure-4wd-camper",
        fuel: "Diesel",
        pax: 2,
        shower: true,
        toilet: false,
        wheel: "4WD",
        transmission: "Automatic",
      },
      supplier: {
        id: "c1efe966-e4f0-4f6a-ab76-1eefd2a05586",
        name: "Apollo",
      },
      age: {
        id: "42bb86c6-7614-47ff-8e70-6eb6fe51433b",
        name: "21+",
      },
      daily: {
        gross: 4288.75,
        nett: 3431,
        profit: 857.75,
        items: [
          {
            day: "2023-10-31T16:00:00.000Z",
            nett: 359,
            gross: 448.75,
            profit: 89.75,
            flex: "H4",
          },
          {
            day: "2023-10-31T16:00:00.000Z",
            nett: 359,
            gross: 448.75,
            profit: 89.75,
            flex: "H4",
          },
          {
            day: "2023-10-31T16:00:00.000Z",
            nett: 359,
            gross: 448.75,
            profit: 89.75,
            flex: "H4",
          },
          {
            day: "2023-10-31T16:00:00.000Z",
            nett: 359,
            gross: 448.75,
            profit: 89.75,
            flex: "H4",
          },
          {
            day: "2023-10-31T16:00:00.000Z",
            nett: 359,
            gross: 448.75,
            profit: 89.75,
            flex: "H4",
          },
          {
            day: "2023-10-31T16:00:00.000Z",
            nett: 359,
            gross: 448.75,
            profit: 89.75,
            flex: "H4",
          },
          {
            day: "2023-10-31T16:00:00.000Z",
            nett: 359,
            gross: 448.75,
            profit: 89.75,
            flex: "H4",
          },
          {
            day: "2023-11-07T16:00:00.000Z",
            nett: 306,
            gross: 382.5,
            profit: 76.5,
            flex: "G6",
          },
          {
            day: "2023-11-07T16:00:00.000Z",
            nett: 306,
            gross: 382.5,
            profit: 76.5,
            flex: "G6",
          },
          {
            day: "2023-11-07T16:00:00.000Z",
            nett: 306,
            gross: 382.5,
            profit: 76.5,
            flex: "G6",
          },
        ],
      },
      fees: {
        total: 2435,
        items: [
          {
            all_depots: false,
            all_dropoffs: null,
            all_suppliers: false,
            all_vehicles: true,
            name: "Broome Location Fee - THL",
            id: "f1eef200-5175-43db-b9d0-4ee6bc0a9b46",
            fee: 835,
            fees_depots: [{ depots: { id: "f9fa3b75-2b65-4882-b8f2-007f941ec5f7", name: "Broome" } }],
            fees_dropoffs: [{ dropoffs: { id: "f9fa3b75-2b65-4882-b8f2-007f941ec5f7", name: "Broome" } }],
            fees_suppliers: [
              { suppliers: { id: "9dc23240-0c2e-4985-91d8-bd9a0b55bd2f", name: "Britz" } },
              { suppliers: { id: "f9498925-e7be-4280-82ce-32c20ca30fca", name: "Maui" } },
            ],
            fees_vehicles: [],
          },
          {
            all_depots: false,
            all_dropoffs: null,
            all_suppliers: false,
            all_vehicles: true,
            name: "Broome Location Fee - Apollo Group",
            id: "b9cbd968-cdd2-4ee5-a4a1-2a46baa61d1d",
            fee: 800,
            fees_depots: [{ depots: { id: "f9fa3b75-2b65-4882-b8f2-007f941ec5f7", name: "Broome" } }],
            fees_dropoffs: [],
            fees_suppliers: [
              { suppliers: { id: "f9498925-e7be-4280-82ce-32c20ca30fca", name: "Maui" } },
              { suppliers: { id: "9dc23240-0c2e-4985-91d8-bd9a0b55bd2f", name: "Britz" } },
            ],
            fees_vehicles: [{ vehicles: { id: "cf254d63-96f0-494a-9ee0-d1f88fd3bd38", name: "Cheapa 4WD Campa 4WD" } }],
          },
          {
            all_depots: false,
            all_dropoffs: null,
            all_suppliers: false,
            all_vehicles: false,
            name: "ADVR Broome Location Fee",
            id: "3e6e2a46-96b6-4298-bc49-fe684c8ecbc7",
            fee: 800,
            fees_depots: [{ depots: { id: "45b3af68-3eb7-4531-887f-b083ba4f504f", name: "Adelaide" } }],
            fees_dropoffs: [
              { dropoffs: { id: "45b3af68-3eb7-4531-887f-b083ba4f504f", name: "Adelaide" } },
              { dropoffs: { id: "874e0387-782c-41d8-a8a8-c1266ab72108", name: "Alice Springs\t" } },
              { dropoffs: { id: "f9fa3b75-2b65-4882-b8f2-007f941ec5f7", name: "Broome" } },
            ],
            fees_suppliers: [
              { suppliers: { id: "7e39ecef-91c4-442b-a996-57d71b8a036d", name: "Adventure Rentals" } },
              { suppliers: { id: "c1efe966-e4f0-4f6a-ab76-1eefd2a05586", name: "Apollo" } },
              { suppliers: { id: "9dc23240-0c2e-4985-91d8-bd9a0b55bd2f", name: "Britz" } },
            ],
            fees_vehicles: [
              { vehicles: { id: "f47c05ce-2bca-4288-a8db-5a2485fd840e", name: " Discovery 4 berth" } },
              {
                vehicles: {
                  id: "01bae244-c771-46eb-a9f6-0bb5e69190e3",
                  name: "ADV 4WD Camper - Mitsubishi Pajero Hardshell Tent",
                },
              },
              { vehicles: { id: "c0c465b8-f276-4a7f-b36e-d3059a75c8bb", name: " Explorer 4 berth " } },
            ],
          },
        ],
      },
      one_way: 3,
      specials: {
        total: 1413.7,
        items: [
          {
            all_depots: true,
            all_dropoffs: true,
            all_suppliers: false,
            all_vehicles: true,
            type: "Long term",
            days: 21,
            factor: "Percentage",
            value: 8,
            type2: null,
            days2: null,
            factor2: null,
            value2: null,
            discount2: false,
            name: "Apollo Long Hire Discount ",
            description: "THL Long Hire Discount. Rental Duration 21+ days = 8% discount off daily vehicle rate only",
            id: "d8ba0d2d-5d48-44cb-9097-e6279e2429ab",
            specials_depots: [],
            specials_dropoffs: [],
            specials_suppliers: [
              { suppliers: { id: "c1efe966-e4f0-4f6a-ab76-1eefd2a05586", name: "Apollo" } },
              { suppliers: { id: "eda56968-b585-42eb-a8f2-bec46f8d2ff8", name: "Cheapa Campa" } },
            ],
            specials_vehicles: [],
            discount_amount: 1413.7,
            discount_list: [],
            active: true,
          },
        ],
      },
      bonds: {},
      addons: {
        "0-0": {
          name: "500-kilometre package",
          description: "500-kilometre package",
          type: "Per Day",
          nett_rate: 216.4,
          gross_rate: 240,
          nett_cap: 0,
          gross_cap: 240,
          qty: 1,
          inclusive: true,
          daily: false,
        },
        "0-1": {
          name: "Camp Chairs",
          description: "Camp Chairs $19.00 each per rental",
          type: "Per Day",
          nett_rate: 17.6,
          gross_rate: 19,
          nett_cap: 0,
          gross_cap: 0,
          qty: 2,
          inclusive: true,
          daily: false,
        },
        "0-2": {
          name: "Camp Table",
          description: "Camp Table $27.00per rental",
          type: "Per Day",
          nett_rate: 24.8,
          gross_rate: 27,
          nett_cap: 0,
          gross_cap: 0,
          qty: 1,
          inclusive: true,
          daily: false,
        },
      },
      terms: {
        name: "Apollo 23/24",
        id: "e445402d-c6f5-47bc-9d94-2fc66575e12d",
        confirmation: null,
        confirmation_terms: "<p></p>",
        summary: "df311184-c970-46e8-a3b4-de6b92ab23a6.pdf",
        summary_terms: "<p></p>",
        counter: "08c79de1-1175-465b-ba68-c726725c0c24.pdf",
        counter_terms: "<p></p>",
        deposit: 100,
        percentage: false,
        balance: 38,
        description: "Booking with a Visa or Mastercard required 2% card merchant fee",
        payment2: true,
        deposit2: 15,
        percentage2: true,
        balance2: 70,
        description2:
          "Booking with a Visa or Mastercard required 2% card merchant fee. Debit/Credit card required for booking form but payment to agent can be via online bank transfer to be  agreed upon with prior notice.",
        payment3: true,
        deposit3: 25,
        percentage3: true,
        balance3: 45,
        description3:
          "Booking with a Visa or Mastercard required 2% card merchant fee. Debit/Credit card required for booking form but payment to agent can be via online bank transfer to be  agreed upon with prior notice.",
        pay_counter: false,
        suppliers: {
          id: "c1efe966-e4f0-4f6a-ab76-1eefd2a05586",
          name: "Apollo",
        },
      },
      bond: {
        all_suppliers: null,
        all_vehicles: null,
        display_name: "Apollo Middle Road",
        id: "b27323cc-1e52-43a1-aa9e-ad53a5b3f8ca",
        nett: 0,
        gross: 0,
        cap: 0,
        deposit: 2500,
        liability: 2500,
        bond: 2500,
        waive_one_way: false,
        description:
          "Bond $2,500\r\nThe maximum charge for Liability Options is 50 days per rental segment.\r\nIf the guest chooses to take ‘The Low Road’ or ‘The Middle Road’ the total Bond will be debited to the credit or debit card immediately.\r\nThe Bond is fully refundable provided our rental contract terms are met.",
        inclusions:
          "Bond is $2,500 as per Terms and Conditions\r\n24hr Roadside Assistance\r\n2WD Unlimited Kilometres \r\n4WD 300 Kilometres per day then 0.55c per KLM\r\nKitchen Kit\r\nGeneral Equipment\r\nPersonal Kit\r\nExtra Driver/Renter",
        packages_suppliers: [
          {
            suppliers: {
              id: "c1efe966-e4f0-4f6a-ab76-1eefd2a05586",
              name: "Apollo",
            },
          },
        ],
        packages_vehicles: [
          {
            vehicles: {
              id: "dbed6fc4-1901-4871-930c-9fd095ec988a",
              name: "Adventure 4wd Camper",
            },
          },
        ],
      },
      driver: {
        age: "31",
        license: "AU/NZ",
      },
      passenger: {
        adult: "1",
        children: "0",
      },
    },
    users: {
      id: "70a1d9f9-3dcf-4d14-9345-fd638b82559f",
      first_name: "YH",
      last_name: "Won",
      email: "won@signature.studio",
      phone: "0123395452",
    },
    status: "Request",
    deposit: 0,
    payment_1: 0,
    payment_2: 0,
    balance: 0,
    nett: 3431,
    gross: 4288.75,
    profit: 857.75,
    discount: 0,
    agent: null,
    agent_fee: 0,
    system_fee: 68.62,
    nett_profit: 789.13,
    refund: null,
    remark: null,
    remark_deposit: null,
    remark_payment_1: null,
    remark_payment_2: null,
    remark_balance: null,
    remark_refund: null,
    paid_deposit: null,
    paid_payment_1: null,
    paid_payment_2: null,
    paid_balance: null,
    add_discount: null,
    add_discount_remark: null,
  },
  vehicle: {
    name: "Adventure 4wd Camper",
    slug: "adventure-4wd-camper",
    image: "8deded15-906e-4e3c-b292-9ad7824d7179.gif",
  },
};
