import dayjs from "dayjs";
export const forms = {
  reference: {
    label: "Reference",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  title: {
    label: "Title",
    placeholder: "",
    type: "select",
    default: null,
    required: true,
    related: false,
    options: [
      {
        id: "Mr",
        name: "Mr",
      },
      {
        id: "Mrs",
        name: "Mrs",
      },
      {
        id: "Ms",
        name: "Ms",
      },
      {
        id: "Dr",
        name: "Dr",
      },
      {
        id: "Master",
        name: "Master",
      },
      {
        id: "Miss",
        name: "Miss",
      },
    ],
    half: false,
  },
  bond: {
    label: "Bond",
    placeholder: "",
    type: "select",
    default: null,
    required: true,
    related: false,
    options: [
      {
        id: "Standard",
        name: "Standard",
      },
      {
        id: "Bond Reduced",
        name: "Bond Reduced",
      },
    ],
  },
  first_name: {
    label: "First Name",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  last_name: {
    label: "Last Name",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  address_1: {
    label: "Address 1",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  address_2: {
    label: "Address 2",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  name: {
    label: "Name",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  city: {
    label: "City / Suburb",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  state: {
    label: "State / Province",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  postcode: {
    label: "Postcode",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  country: {
    label: "Country",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  phone: {
    label: "Phone",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  email: {
    label: "Email",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  arrival_by: {
    label: "Means of Travel",
    placeholder: "",
    type: "select",
    default: null,
    required: true,
    related: false,
    options: [
      {
        id: "Not specified",
        name: "Not specified",
      },
      {
        id: "Arriving by air",
        name: "Arriving by air",
      },
      {
        id: "Arriving by bus",
        name: "Arriving by bus",
      },
      {
        id: "Arriving by rail / train",
        name: "Arriving by rail / train",
      },
      {
        id: "Driving",
        name: "Driving",
      },
    ],
    half: false,
  },
  flexibility: {
    label: "Flexibility",
    placeholder: "",
    type: "select",
    default: null,
    required: true,
    related: false,
    options: [
      {
        id: "Not flexible",
        name: "Not flexible",
      },
      {
        id: "1 day",
        name: "1 day",
      },
      {
        id: "2 days",
        name: "2 days",
      },
      {
        id: "3 days",
        name: "3 days",
      },
      {
        id: "4 - 6 days",
        name: "4 - 6 days",
      },
      {
        id: "1 week or more",
        name: "1 week or more",
      },
    ],
    half: false,
  },
  arrival_date: {
    label: "Arrival Date",
    placeholder: "",
    type: "date",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  arrival_flight: {
    label: "Flight Arrival Details",
    placeholder: "",
    type: "textarea",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  suppliers: {
    label: "Supplier",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "suppliers",
    options: false,
    half: false,
  },
  categories: {
    label: "Category",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "categories",
    options: false,
    half: false,
  },
  vehicles: {
    label: "Vehicle",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "vehicles",
    options: false,
    half: false,
  },
  licenses: {
    label: "License",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "constants",
    options: [{ name: "type", value: "licenses" }],
    half: true,
  },
  pickup_date: {
    label: "Pick-up date",
    placeholder: "",
    type: "daterange",
    default: dayjs(),
    required: false,
    related: false,
    options: false,
    half: false,
  },
  pickup_depot: {
    label: "Pick-up depot",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "depots",
    options: false,
    half: true,
  },
  dropoff_date: {
    label: "Drop-off date",
    placeholder: "",
    type: "daterange",
    default: dayjs(),
    required: false,
    related: false,
    options: false,
    half: false,
  },
  dropoff_depot: {
    label: "Drop-off depot",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "depots",
    options: false,
    half: true,
  },
  count_adults: {
    label: "Adults",
    placeholder: "",
    type: "number",
    default: null,
    required: true,
    related: false,
    options: false,
    half: true,
  },
  count_children: {
    label: "Childrens",
    placeholder: "",
    type: "number",
    default: null,
    required: true,
    related: false,
    options: false,
    half: true,
  },
  bonds: {
    label: "Bond",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "packages",
    options: false,
    half: false,
  },
  comments: {
    label: "Comments",
    placeholder: "",
    type: "textarea",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  guests: {
    label: "Guests",
    placeholder: "",
    type: "json",
    default: null,
    required: true,
    related: false,
    options: [
      {
        key: "title",
        label: "Title",
        placeholder: "",
        type: "select",
        default: null,
        required: false,
        related: false,
        options: [
          {
            id: "Mr",
            name: "Mr",
          },
          {
            id: "Mrs",
            name: "Mrs",
          },
          {
            id: "Ms",
            name: "Ms",
          },
          {
            id: "Dr",
            name: "Dr",
          },
          {
            id: "Master",
            name: "Master",
          },
          {
            id: "Miss",
            name: "Miss",
          },
        ],
        half: true,
      },
      {
        key: "age",
        label: "Age",
        placeholder: "",
        type: "number",
        default: null,
        required: false,
        related: false,
        options: false,
        half: true,
      },
      {
        key: "name",
        label: "Name",
        placeholder: "",
        type: "text",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
    ],
    half: false,
  },
  pay_arrangement: {
    label: "Payment Arrangements",
    placeholder: "",
    type: "select",
    default: null,
    required: true,
    related: false,
    options: [
      {
        id: "A - Deposit to agent at booking, balance to supplier at pickup as per quote",
        name: "A - Deposit to agent at booking, balance to supplier at pickup as per quote",
      },
      {
        id: "B - Full Payment at time of booking - Booking deposit to agent and balance to supplier as per quote",
        name: "B - Full Payment at time of booking - Booking deposit to agent and balance to supplier as per quote",
      },
      {
        id: "C - 20% booking deposit or as nominated to agent, balance 35 days prior to pickup or as nominated date on your quote",
        name: "C - 20% booking deposit or as nominated to agent, balance 35 days prior to pickup or as nominated date on your quote",
      },
    ],
    half: false,
  },
  pay_amount: {
    label: "Amount to Pay",
    placeholder: "",
    type: "number",
    default: null,
    required: true,
    related: false,
    options: 0.01,
    half: false,
  },
  type: {
    label: "Type",
    placeholder: "",
    type: "hidden",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  ages: {
    label: "Age",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "constants",
    options: [{ name: "type", value: "ages" }],
    half: true,
  },
  card_type: {
    label: "Card Type",
    placeholder: "",
    type: "select",
    default: null,
    required: true,
    related: false,
    options: [
      {
        id: "MasterCard",
        name: "MasterCard",
      },
      {
        id: "Visa",
        name: "Visa",
      },
    ],
    half: false,
  },
  card_name: {
    label: "Name on Card",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  card_number: {
    label: "Card Number",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  card_month: {
    label: "Card Expiry Month",
    placeholder: "",
    type: "number",
    default: null,
    required: true,
    related: false,
    options: false,
    half: true,
  },
  card_year: {
    label: "Card Expiry Year",
    placeholder: "",
    type: "number",
    default: null,
    required: true,
    related: false,
    options: false,
    half: true,
  },
  card_code: {
    label: "Security Code (CVV)",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  card_comments: {
    label: "Card Comments",
    placeholder: "",
    type: "textarea",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
};
