import dayjs from "dayjs";
export const packages = {
  display_name: {
    label: "Display Name",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  name: {
    label: "Name",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  description: {
    label: "Description",
    placeholder: "",
    type: "textarea",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  date_start: {
    label: "Start date",
    placeholder: "",
    type: "daterange",
    default: dayjs(),
    required: false,
    related: false,
    options: false,
    half: false,
  },
  date_end: {
    label: "End date",
    placeholder: "",
    type: "daterange",
    default: dayjs(),
    required: false,
    related: false,
    options: false,
    half: false,
  },
  nett: {
    label: "Nett Daily Rate",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: 0.01,
    half: true,
  },
  gross: {
    label: "Gross Daily Rate",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: 0.01,
    half: true,
  },
  cap: {
    label: "Rate Cap (Days)",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: false,
    half: true,
  },
  deposit: {
    label: "Security Deposit",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: 0.01,
    half: true,
  },
  liability: {
    label: "Liability",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: 0.01,
    half: true,
  },
  bond: {
    label: "Bond",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: 0.01,
    half: true,
  },
  waive_one_way: {
    label: "Waive one-way fee",
    placeholder: "",
    type: "switch",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  inclusions: {
    label: "Inclusions",
    placeholder: "",
    type: "textarea",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  code: {
    label: "Code",
    placeholder: "",
    type: "text",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  compulsory: {
    label: "compulsory",
    placeholder: "",
    type: "json",
    default: null,
    required: true,
    related: false,
    options: [
      {
        key: "Name",
        label: "",
        placeholder: "Name",
        type: "text",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
      {
        label: "",
        key: "Description",
        placeholder: "Description",
        type: "textarea",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
      {
        key: "Nett Rate",
        label: "Nett Rate",
        placeholder: "",
        type: "number",
        default: null,
        required: false,
        related: false,
        options: 0.01,
        half: true,
      },
      {
        key: "Gross Rate",
        label: "Gross Rate",
        placeholder: "",
        type: "number",
        default: null,
        required: false,
        related: false,
        options: 0.01,
        half: true,
      },
      {
        key: "Quantity",
        label: "Quantity",
        placeholder: "",
        type: "number",
        default: null,
        required: false,
        related: false,
        options: false,
        half: true,
      },
    ],
    half: false,
  },
  all_vehicles: {
    label: "Vehicles",
    placeholder: "",
    type: "many",
    default: false,
    required: false,
    related: false,
    options: "packages_vehicles",
    half: false,
  },
  all_suppliers: {
    label: "Suppliers",
    placeholder: "",
    type: "many",
    default: false,
    required: false,
    related: false,
    options: "packages_suppliers",
    half: false,
  },
  rank: {
    label: "Rank",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: false,
    half: true,
  },
  status: {
    label: "Status",
    placeholder: "",
    type: "switch",
    default: true,
    required: false,
    related: false,
    options: "Active",
    half: true,
  },
};
