import dayjs from "dayjs";
export const routes = {
  name: {
    label: "Name",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  date_start: {
    label: "Start date",
    placeholder: "",
    type: "daterange",
    default: dayjs(),
    required: false,
    related: false,
    options: false,
    half: false,
  },
  date_end: {
    label: "End date",
    placeholder: "",
    type: "daterange",
    default: dayjs(),
    required: false,
    related: false,
    options: false,
    half: false,
  },
  all_depots: {
    label: "Depots",
    placeholder: "",
    type: "many",
    default: false,
    required: false,
    related: false,
    options: "routes_depots",
    half: false,
  },
  all_suppliers: {
    label: "Suppliers",
    placeholder: "",
    type: "many",
    default: false,
    required: false,
    related: false,
    options: "routes_suppliers",
    half: false,
  },
  routes: {
    label: "Routes",
    placeholder: "",
    type: "routes",
    default: false,
    required: false,
    related: false,
    options: false,
    half: false,
  },
};
