export const suppliers = {
  name: {
    label: "Name",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  url: {
    label: "Check-in URL",
    placeholder: "",
    type: "text",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  phone: {
    label: "Customer Service Number",
    placeholder: "",
    type: "text",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  depots: {
    label: "Depots",
    placeholder: "",
    type: "json",
    default: [],
    required: false,
    related: false,
    options: [
      {
        key: "Depots",
        label: "Depots",
        placeholder: "",
        type: "related",
        default: null,
        required: false,
        related: "depots",
        options: false,
        half: false,
      },
      {
        key: "Address",
        label: "Address",
        placeholder: "Address",
        type: "textarea",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
      {
        key: "Contact (International)",
        label: "Contact (International)",
        placeholder: "Contact (International)",
        type: "text",
        default: null,
        required: false,
        related: false,
        options: false,
        half: true,
      },
      {
        key: "Contact (Australia)",
        label: "Contact (Australia)",
        placeholder: "Contact (Australia)",
        type: "text",
        default: null,
        required: false,
        related: false,
        options: false,
        half: true,
      },
    ],
    half: false,
  },
  status: {
    label: "Status",
    placeholder: "",
    type: "switch",
    default: true,
    required: false,
    related: false,
    options: "Active",
    half: true,
  },
  rank: {
    label: "Rank",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: false,
    half: true,
  },
};
