export const vehicles = {
  name: {
    label: "Name",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  code: {
    label: "Code",
    placeholder: "",
    type: "text",
    default: null,
    required: true,
    related: false,
    options: false,
    half: false,
  },
  suppliers: {
    label: "Supplier",
    placeholder: "",
    type: "related",
    default: null,
    required: false,
    related: "suppliers",
    options: false,
    half: false,
  },
  status: {
    label: "Status",
    placeholder: "",
    type: "switch",
    default: true,
    required: false,
    related: false,
    options: "Active",
    half: true,
  },
  rank: {
    label: "Rank",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: false,
    half: true,
  },
  image: {
    label: "Featured Image",
    placeholder: "",
    type: "image",
    default: null,
    required: false,
    related: false,
    options: "contents",
    half: false,
  },
  caption: {
    label: "Caption",
    placeholder: "",
    type: "text",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  pax: {
    label: "Pax",
    placeholder: "",
    type: "number",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  transmission: {
    label: "Transmission",
    placeholder: "",
    type: "select",
    default: null,
    required: false,
    related: false,
    options: [
      {
        id: "Automatic",
        name: "Automatic",
      },
      {
        id: "Manual",
        name: "Manual",
      },
    ],
    half: false,
  },
  fuel: {
    label: "Fuel",
    placeholder: "",
    type: "select",
    default: null,
    required: false,
    related: false,
    options: [
      {
        id: "Diesel",
        name: "Diesel",
      },
      {
        id: "Petrol",
        name: "Petrol",
      },
    ],
    half: false,
  },
  wheel: {
    label: "Driven Wheel",
    placeholder: "",
    type: "select",
    default: null,
    required: false,
    related: false,
    options: [
      {
        id: "4WD",
        name: "4WD",
      },
      {
        id: "2WD",
        name: "2WD",
      },
    ],
    half: false,
  },
  shower: {
    label: "Shower",
    placeholder: "",
    type: "switch",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  toilet: {
    label: "Toilet",
    placeholder: "",
    type: "switch",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  excerpt: {
    label: "Short Description",
    placeholder: "",
    type: "text",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  description: {
    label: "Description",
    placeholder: "",
    type: "richtext",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  restrictions: {
    label: "Restrictions",
    placeholder: "",
    type: "richtext",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  notes: {
    label: "Notes",
    placeholder: "",
    type: "richtext",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
  specifications: {
    label: "Specifications",
    placeholder: "",
    type: "json",
    default: [],
    required: false,
    related: false,
    options: [
      {
        key: "Title",
        label: "Title",
        placeholder: "",
        type: "text",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
      {
        key: "Description",
        label: "Description",
        placeholder: "",
        type: "textarea",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
    ],
    half: false,
  },
  faqs: {
    label: "FAQs",
    placeholder: "",
    type: "json",
    default: [],
    required: false,
    related: false,
    options: [
      {
        key: "Title",
        label: "Title",
        placeholder: "",
        type: "text",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
      {
        key: "Question",
        label: "Question",
        placeholder: "",
        type: "textarea",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
      {
        key: "Answer",
        label: "Answer",
        placeholder: "",
        type: "textarea",
        default: null,
        required: false,
        related: false,
        options: false,
        half: false,
      },
    ],
    half: false,
  },
  images: {
    label: "Images",
    placeholder: "",
    type: "gallery",
    default: [],
    required: false,
    related: false,
    options: false,
    half: false,
  },
  type: {
    label: "Type",
    placeholder: "",
    type: "hidden",
    default: "vehicles",
    required: false,
    related: false,
    options: false,
    half: false,
  },
  slug: {
    label: "Slug",
    placeholder: "",
    type: "hidden",
    default: null,
    required: false,
    related: false,
    options: false,
    half: false,
  },
};
